# Programming Assignment 5
---
**Author:** Nikola Mrdak  
**Version:** 1.0  
**Semester:** Spring 2024 

This *notebook* contains my solution(s) to **Programming Assignment 5**

In [8]:
import numpy as np

### Problem 1 - Language Translator

In [3]:
dictionary={
    "hola":"hello",
    "adios":"goodbye",
    "gracias":"thank you",
    "por favor":"please",
    "si":"yes",
    "no":"no",
    "familia":"family",
    "amor":"love",
    "comida":"food",
    "agua":"water",
    "casa":"house",
    "trabaio":"work",
    "escuela":"school",
    "dinero":"money",
    "tiempo":"time",
    "dia":"day",
    "noche":"night",
    "semana":"week",
    "mes":"month",
    "ano":"year"
     }

In [ ]:
translator = input(f'Enter a word to translate from English to Spanish (enter Q to quit):')
while translator !='Q':    
    if translator in dictionary.values()==True:
        for spanish, english in dictionary.items():
            #if english == translator
            print(f'The Spanish word for {english} is {spanish}.')
    
    else:
        print(f'The Spanish word for {translator} is not in this dictionary.')

    input(f'Enter a word to translate from English to Spanish (enter Q to quit):')

print(f'Biligual Master!')
#I was unable to solve this problem. 

Enter a word to translate from English to Spanish (enter Q to quit): hello


The Spanish word for hello is not in this dictionary.


Enter a word to translate from English to Spanish (enter Q to quit): Q


The Spanish word for hello is not in this dictionary.


### Problem 2 - Translating Morse Code

### Problem 3 - Comparing Minors/Majors

In [ ]:
ComputerMinor = {}
AdministrationMinor = {}
AnalyticsMinor = {}
DataScienceMajor = {}

### Problem 4 - Working with NumPy

In [11]:
#np.dot?

#### a)

In [19]:
A1 = np.random.randint(0,20, size = (5,5))
A2 = np.random.randint(0,20, size = (5,5))

In [2]:
#A1,A2

In [24]:
MatrixProduct = np.dot(A1, A2)

In [26]:
DotProduct = np.dot(A1.flatten(), A2.flatten())

In [37]:
print(f'Matrix Product:{MatrixProduct}')
print(f'Dot Product: {DotProduct}')

Matrix Product:[[637 652 485 478 952]
 [387 291 249 340 489]
 [328 234 173 310 443]
 [572 330 281 506 635]
 [481 376 344 322 621]]
Dot Product: 2046


#### b)

In [23]:
print(np.linalg.det(A1))
print(np.linalg.det(A2))

228629.99999999985
-45375.9999999999


In [24]:
print(np.linalg.inv(A1))
print(np.linalg.inv(A2))

[[ 0.01157328  0.05461226 -0.01487994 -0.00984123  0.01215064]
 [ 0.12384202 -0.07547566  0.07886979 -0.07129423 -0.08086428]
 [ 0.02981236 -0.04412807 -0.0621397  -0.00494248  0.09365788]
 [-0.14121506  0.0932686  -0.00891397  0.140489   -0.03034597]
 [ 0.05731531 -0.03906312  0.09297555 -0.09635656 -0.01125399]]
[[-0.00493653  0.29619182 -0.03949224 -0.17771509  0.09943583]
 [-0.27444023  0.90391396 -0.00802186 -0.41109838  0.2155104 ]
 [ 0.05875353 -0.40021157  0.09502821  0.17762694 -0.12989245]
 [ 0.24647391 -0.78843441 -0.02820874  0.37306065 -0.10754584]
 [-0.00191731 -0.07246121  0.0471615   0.08722673 -0.11316555]]


#### c)

In [26]:
Array1 = np.linspace(0.0,1.0, num = 20)


In [25]:
Array2 = np.linspace(1.0,2.0, num = 20)


In [15]:
Array3 = np.hstack((Array1,Array2)).reshape(10,4)
Array3

array([[0.        , 0.05263158, 0.10526316, 0.15789474],
       [0.21052632, 0.26315789, 0.31578947, 0.36842105],
       [0.42105263, 0.47368421, 0.52631579, 0.57894737],
       [0.63157895, 0.68421053, 0.73684211, 0.78947368],
       [0.84210526, 0.89473684, 0.94736842, 1.        ],
       [1.        , 1.05263158, 1.10526316, 1.15789474],
       [1.21052632, 1.26315789, 1.31578947, 1.36842105],
       [1.42105263, 1.47368421, 1.52631579, 1.57894737],
       [1.63157895, 1.68421053, 1.73684211, 1.78947368],
       [1.84210526, 1.89473684, 1.94736842, 2.        ]])